
services:
  teleport:
    image: public.ecr.aws/gravitational/teleport-distroless:13
    container_name: teleport
    volumes:
      - ./config:/etc/teleport
      - ./data:/var/lib/teleport
    # -- (Optional) Traefik example configuration
    labels:
       - "traefik.enable=true"
       - "traefik.http.services.teleport.loadbalancer.server.port=3080"
       - "traefik.http.services.teleport.loadbalancer.server.scheme=https"
       - "traefik.http.routers.teleport-http.entrypoints=web"
       - "traefik.http.routers.teleport-http.rule=HostRegexp(`your-server-url`, `{subhost:[a-z]+}.your-server-url`)"
       - "traefik.http.routers.teleport-https.entrypoints=websecure"
       - "traefik.http.routers.teleport-https.rule=HostRegexp(`your-server-url`, `{subhost:[a-z]+}.your-server-url`)"
       - "traefik.http.routers.teleport-https.tls=true"
       - "traefik.http.routers.teleport-https.tls.certresolver=your-certresolver"
       - "traefik.http.routers.teleport-https.tls.domains[0].main=your-server-url"
       - "traefik.http.routers.teleport-https.tls.domains[0].sans=*.your-server-url"
